### ISSUE TITLE
llamada recursiva

### ISSUE THREAD

**Issue by sergioviera** [dds-frd-utn/BancoBalorant_Grupo2#1]
Dentro de la definición de un método REST se llama a otro método REST... esto además de no ser performante puede generar problemas en el acceso a la base de datos.

https://github.com/dds-frd-utn/BancoBalorant_Grupo2/blob/aaa2fc68cf16c6171e6dbaf81da86754a34ee7a6/src/main/java/utn/frd/bancogrupo2/rest/services/MovimientoRest.java#L261

**Comment by davidmarco12** [comment]
En vez de hacer un metodo REST, utilizar las querys creadas para las cuentas usando id_cuenta.
Usando CuentaFacade, se puede utilizar el metodo find(id).

private CuentasFacade ejbCuentaFacade;

respuestaOrigen =  ejbCuentaFacade.find(id_cuenta);
