### ISSUE TITLE
Logout después de login

### ISSUE THREAD

**Issue by sergioviera** [dds-frd-utn/BancoBalorant_Grupo2#2]
En la misma acción que se hace el login se hace un logout... 

https://github.com/dds-frd-utn/BancoBalorant_Grupo2/blob/aaa2fc68cf16c6171e6dbaf81da86754a34ee7a6/src/main/webapp/funciones.js#L142

**Comment by davidmarco12** [comment]
Eliminar funcion realizarLogin, ya que devuelve un error, e insertar location.href = "user/index.html";
