### ISSUE TITLE
llamadas ajax

### ISSUE THREAD

**Issue by sergioviera** [dds-frd-utn/BancoBalorant_Grupo2#3]
Se hacen llamadas ajax usando javascript nativo:
https://github.com/dds-frd-utn/BancoBalorant_Grupo2/blob/master/src/main/webapp/user/js/index.js#L106

y jquery:
https://github.com/dds-frd-utn/BancoBalorant_Grupo2/blob/master/src/main/webapp/funciones.js#L110

**Comment by davidmarco12** [comment]
Cambiar las llamadas de javascript nativo por las jquery.
Ejemplo: 
$.ajax({
            url:"http://localhost:8080/bancogrupo2/rest/movimientos/realizar",
            method:"post",
            data:data,
            dataType:"json",
            contentType:"application/json",
            async:false,
            success:function(){
               alert("Movimiento Realizado");     
            },
            error:function(error){
                alert("Ha ocurrido un error");
                console.log(error);
            }
  });
